config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [] do
    resources :items, only: :create
  end

  resources :items, only: [] do
    resources :completes, only: [:create, :destroy]

    collection do
      delete 'destroy_multiple'
    end
  end

  get 'users/:id' => 'users#show', as: :user_show
  get 'auto_sign' => 'welcome#auto_sign'

  root 'welcome#index'
end

app/models/complete.rb
class Complete < ActiveRecord::Base
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  has_many :completes, dependent: :destroy

  validates :name, length: { minimum: 1 }, presence: true
  validates :user, presence: true

  default_scope { order('created_at ASC') }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :items, dependent: :destroy
  has_many :completes, dependent: :destroy

  def avatar_url(size)
    gravatar_id = Digest::MD5::hexdigest(self.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end

  def complete_for(item)
    completes.find_by(item_id: item.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    user_show_path(resource)
  end
end


# Other way to use after_sign_in_path_for
# user_path(current_user)
#
# def after_sign_in_path_for(resource)
#  items_path
# end

app/controllers/completes_controller.rb
class CompletesController < ApplicationController
  def create
    @item = Item.find(params[:item_id])
    @complete = @item.completes.build(user: current_user)

    if @complete.save
      @msg = "Complete item: #{@item.name}"
    else
      @msg = "Completing failed"
    end

    respond_to do |format|
      format.html { redirect_to user_show_path(current_user) }
      format.js
    end
  end

  def destroy
    @item = Item.find(params[:item_id])
    @complete = @item.completes.find(params[:id])

    if @complete.destroy
      @msg = "Incomplete item: #{@item.name}"
    else
      @msg = "Incompleting failed"
    end

    respond_to do |format|
      format.html { redirect_to user_show_path(current_user) }
      format.js
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @item = current_user.items.build(item_params)
    @new_item = Item.new

    if @item.save
      @msg = "Saved! New Item: #{@item.name}"
    else
      @msg = 'Item failed to save.'
    end

    respond_to do |format|
      format.html { redirect_to user_show_path(current_user) }
      format.js
    end
  end

  def destroy_multiple
    # select returns an array, not association
    # array won't work with destroy_all(association can)
    @items = current_user.items.select {|i| i.completes.any? }

    if @items.each(&:destroy)
      @msg = "Deleted! Item(s): " + @items.map(&:name).join(', ')
    else
      @msg = 'Item failed to delete'
    end

    respond_to do |format|
      format.html { redirect_to user_show_path(current_user) }
      format.js
    end
  end

  private
  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @tester = User.find_by(email: "test@test.io")
  end

  def auto_sign
    tester = User.find_by(email: "test@test.io")
    sign_in(tester)
    flash[:notice] = "You are signed in as test user."
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/completes_helper.rb
module CompletesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/completes/_complete.html.erb
<div id="item-<%= item.id %>-complete">
  <% if complete = current_user.complete_for(item) %>
    <%= link_to "", [item, complete], method: :delete, remote: true, class: 'glyphicon glyphicon-ok', style: 'float: left; color: #449d44;' %>
  <% else %>
    <%= link_to "", [item, Complete.new], method: :post, remote: true, class: 'glyphicon glyphicon-remove', style: 'float: left; color: #aaa;' %>
  <% end %>
</div>

app/views/completes/create.js.erb
<% if Complete.exists?(id: @complete.id) %>
  $('.flash').html("<div class='alert alert-success'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= @msg %></div>");
  $('#item-<%= @item.id %>-complete').html("<%= escape_javascript(link_to "", [@item, @complete], method: :delete, remote: true, class: 'glyphicon glyphicon-ok', style: 'float: left; color: #449d44;') %>")
<% else %>
  $('.flash').html("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= @msg %></div>");
<% end %>

app/views/completes/destroy.js.erb
<% if @complete.destroyed? %>
  $('.flash').html("<div class='alert alert-success'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= @msg %></div>");
  $('#item-<%= @item.id %>-complete').html("<%= escape_javascript(link_to "", [@item, Complete.new], method: :post, remote: true, class: 'glyphicon glyphicon-remove', style: 'float: left; color: #aaa;') %>")
<% else %>
  $('.flash').html("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= @msg %></div>");
<% end %>

app/views/items/_form.html.erb
<section id="addNew">
  <div class="panel-heading">
    <h3 class="panel-title">Add a new item to do</h3>
  </div>
  <div class="panel-body">
    <%= form_for [current_user, item], remote: true, html: { class: 'form-inline' } do |f| %>
      <div class="form-group">
        <%= f.label :name, class: 'sr-only' %>
        <%= f.text_field :name, class: 'form-control', placeholder: 'Enter a new item to do', style: 'width: 600px;' %>
      </div>
      <%= button_tag(type: 'submit', class: 'btn btn-default') do %>
        Submit
      <% end %>
    <% end %>
  </div>
</section>

app/views/items/_item.html.erb
<%= content_tag :li, class: 'list-group-item', id: "item-#{item.id}" do %>
  <span class="badge"><%= distance_of_time_in_words(Time.now, item.created_at) %> ago</span>
  <%= render partial: 'completes/complete', locals: { item: item } %>
  <p style='margin-left: 30px;'><%= item.name %></p>
<% end %>

app/views/items/create.js.erb
<% if @item.valid?  %>
  $('.flash').html("<div class='alert alert-success'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= @msg %></div>");
  $('.js-items').append("<%= escape_javascript(render(@item)) %>");
  $('.new-item').html("<%= escape_javascript(render partial: 'items/form', locals: { item: @new_item }) %>");
<% else %>
  $('.flash').html("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= @msg %></div>");
  $('.new-item').html("<%= escape_javascript(render partial: 'items/form', locals: { item: @new_item }) %>");
<% end  %>

app/views/items/destroy_multiple.js.erb
<% items = current_user.items.select {|i| i.completes.any? } %>
<% if items.empty? %>
  <% @items.each do |i| %>
    $('#item-<%= i.id %>').hide();
  <% end %>
  $('.flash').html("<div class='alert alert-success'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= @msg %></div>");
<% else %>
  $('.flash').html("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= @msg %></div>");
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>TodoApp</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Todo App</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <% if user_signed_in? %>
            <ul class="nav navbar-nav">
              <li><%= link_to "Todo List", user_show_path(current_user) %></li>
            </ul>
          <% end %>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "My Todo List", user_show_path(current_user) %></li>
              <li><%= link_to 'Edit profile', edit_user_registration_path, class: 'navbar-link' %></li>
              <li><%= link_to 'Sign Out', destroy_user_session_path, class: 'navbar-link', method: :delete %></li>
            <% else %>
              <li><%= link_to 'Sign Up', new_user_registration_path, class: 'navbar-link' %></li>
              <li><%= link_to 'Sign In', new_user_session_path, class: 'navbar-link' %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <div class="flash">
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash.now[:alert] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash.now[:alert] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>

    <%= yield %>
  </div>
</body>
</html>

app/views/users/show.html.erb
<div class="user-profile">
  <div class="media pull-left">
    <% avatar_url = current_user.avatar_url(230) %>
    <% if avatar_url %>
      <%= image_tag avatar_url, class: 'meida-object gravatar_lg' %>
    <% end %>

    <h4><%= current_user.email %></h4>
    <hr>
    <p><span class="glyphicon glyphicon-tasks"></span> Number of sign in: <%= current_user.sign_in_count %></p>
    <hr>
    <p><span class="glyphicon glyphicon-time"></span> Join on: <%= current_user.created_at.strftime("%B %d, %Y") %></p>
    <hr>

  </div>
  <div class="col-md-9 pull-right">
    <div class="well">
      Delete all the complete to-do items
      <%= link_to destroy_multiple_items_path, method: :delete, remote: true, class: 'btn btn-warning', style: 'float: right;' do %>
        <span class="glyphicon glyphicon-trash"></span> Delete
      <% end %>
    </div>
    <div class="items">
      <li class="list-group-item disabled">
        Your To-Do Items
        <small>
          <span class="glyphicon glyphicon-ok"></span> Complete |
          <span class="glyphicon glyphicon-remove"></span> Incomplete
        </small>
      </li>
      <ul class="list-group js-items">
        <% current_user.items.each do |item| %>
          <%= render partial: 'items/item', locals: { item: item } %>
        <% end %>
      </ul>
    </div>
    <div class="panel panel-default new-item">
      <%= render partial: 'items/form', locals: { item: current_user.items.new } %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h2>To Do List</h2>
  <p class="lead">Make your own to-do list. Start today!</p>
  <p>A self-destructing to-do list to keep you focused on the things that really matter.</p>

  <a href="http://todo-app-ghbooth12.herokuapp.com" target="_blank" class="btn btn-info">GitHub</a>
  <%= link_to "Log in as test user automatically", auto_sign_path, class: 'btn btn-warning' %>
  <%= link_to "See Todo List", user_show_path(@tester), class: 'btn btn-success' %>
</div>

<div id="steps" class="row">
  <div class="col-xs-12">
    <div class="panel">
      <div class="panel-heading">
        <h2><strong>How it works</strong></h2>
        <p>Log-in as test user account, take a look how it works.</p>
      </div>
      <div class="panel-body">
        <div class="well">
          <ol class="hover-link">
            <li>
              <%= link_to auto_sign_path do %>
                Click here to log in automatically. <span class="glyphicon glyphicon-link" aria-hidden="true"></span>
              <% end %>
            </li>
            <li>
              <%= link_to user_show_path(@tester), target: '_blank' do %>
                See to-do list. <span class="glyphicon glyphicon-link" aria-hidden="true"></span>
              <% end %>
            </li>
            <li>
              Upload profile photo through <a href="https://en.gravatar.com" target="_blank">Gravatar</a>.
            </li>
            <li>
              <%= link_to user_show_path(id: @tester, anchor: "addNew"), target: '_blank' do %>
                Add a new to-do item. <span class="glyphicon glyphicon-link" aria-hidden="true"></span>
              <% end %>
            </li>
            <li>
              <%= link_to user_show_path(@tester), target: '_blank' do %>
                Check off the completed to-do items. Ajax makes buttons much faster. <span class="glyphicon glyphicon-link" aria-hidden="true"></span>
              <% end %>
            </li>
            <li>
              <%= link_to user_show_path(@tester), target: '_blank' do %>
                With Rake, delete to-do items Automatically that have not been completed after seven days. <span class="glyphicon glyphicon-link" aria-hidden="true"></span>
              <% end %>
            </li>
          </ol>
        </div>
      </div>
    </div>
  </div>
</div>